language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - git clone https://github.com/pedrocr/imagepipe.git
  - git clone https://github.com/pedrocr/rawloader.git imagepipe/rawloader/
  - git clone https://github.com/pedrocr/multicache.git imagepipe/multicache/
notifications:
  email:
    recipients:
      - pedro@pedrocr.net
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.mozilla.org#chimper"
    on_success: change
    on_failure: always
    skip_join: true
if: tag IS blank
