language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - git clone https://github.com/pedrocr/imagepipe.git ../imagepipe/
  - git clone https://github.com/pedrocr/rawloader.git ../rawloader/
  - git clone https://github.com/pedrocr/multicache.git ../multicache/
  - sudo apt-get update
  - sudo apt-get -y install libxcb-shape0-dev libxcb-xfixes0-dev
notifications:
  email:
    recipients:
      - pedro@pedrocr.net
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.libera.chat#chimper"
    on_success: change
    on_failure: always
    skip_join: true
if: tag IS blank
