[package]
name = "chimper"
version = "0.3.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]
description = "A graphical image viewer"
#homepage = "..."
repository = "https://github.com/pedrocr/chimper"
license = "GPL-3.0"
categories = ["multimedia::images"]

[dependencies]
image = "0.21"
rand = "0.6"
crossbeam-utils = "0.6"
conrod_core = "0.66"
conrod_glium = "0.66"
conrod_winit = "0.66"
glium = "0.24"
winit = "0.19"

[dependencies.imagepipe]
version = "0.3.0"
path = "./imagepipe"

[dependencies.multicache]
version = "0.6.0"
path = "./imagepipe/multicache"

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
opt-level = 3

[[bin]]
name = "chimper"
doc = false
