[package]
name = "chimper"
version = "0.1.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]
description = "A graphical image viewer"
#homepage = "..."
repository = "https://github.com/pedrocr/chimper"
license = "GPL-2.1"
categories = ["multimedia::images"]

[dependencies]
rawloader = "0.33.0"
image = "0.15.0"
rand = "0.3.16"
crossbeam = "0.3.0"
rusttype = "0.2.1"
multicache = "0.4.1"

[dependencies.conrod]
version = "0.54.0"
features = ["glium", "winit"]

[replace]
#"glium:0.16.0"  = { git = 'https://github.com/tomaka/glium.git', branch='master'}
#"rawloader:0.31.0"  = { git = 'https://github.com/pedrocr/rawloader.git', branch='master'}
#"winit:0.5.10"  = { git = 'https://github.com/pedrocr/winit.git', branch='maximization' }
#"glutin:0.7.4" = { git = 'https://github.com/pedrocr/glutin.git', branch='maximization' }
#"image:0.12.2" = { path = '../image/' }

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
opt-level = 3

[[bin]]
name = "chimper"
doc = false

[[bin]]
name = "test"
doc = false
