[package]
name = "chimper"
version = "0.1.2"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]
description = "A graphical image viewer"
#homepage = "..."
repository = "https://github.com/pedrocr/chimper"
license = "GPL-3.0"
categories = ["multimedia::images"]

[dependencies]
image = "0.19"
rand = "0.5"
crossbeam-utils = "0.5"
multicache = "0.4"
imagepipe = "0.1"

[dependencies.conrod]
version = "0.61"
features = ["glium", "winit"]

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
opt-level = 3

[[bin]]
name = "chimper"
doc = false

[[bin]]
name = "test"
doc = false

[[bin]]
name = "test_awakened"
doc = false

[[bin]]
name = "test_evloop"
doc = false
