[package]
name = "chimper"
version = "0.1.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]
description = "A graphical image viewer"
#homepage = "..."
repository = "https://github.com/pedrocr/chimper"
license = "GPL-2.1"
categories = ["multimedia::images"]

[dependencies]
rawloader = "0.33.0"
image = "0.19.0"
rand = "0.4.2"
crossbeam = "0.3.2"
rusttype = "0.5.2"
multicache = "0.4.1"

[dependencies.conrod]
version = "0.59.1"
features = ["glium", "winit"]

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
opt-level = 3

[[bin]]
name = "chimper"
doc = false

[[bin]]
name = "test"
doc = false

[[bin]]
name = "test_awakened"
doc = false

[[bin]]
name = "test_evloop"
doc = false
